version: '3.4'
services:
  api:
    platform: "linux/amd64"
    image: 559674923590.dkr.ecr.us-east-1.amazonaws.com/sept-temaproject:g07-04
    ports:
      - "8080:8080"
    environment:
     spring.datasource.url: jdbc:mysql://database:3306/userdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
     spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
     spring.datasource.username: root
     spring.datasource.password: ${DB_PASSWORD}
    depends_on:
      - database
  database:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  db: