CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    wishlist VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS colesproducts (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    item VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    description TEXT NULL,
    img_url VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS woolsproducts (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    item VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    description TEXT NULL,
    img_url VARCHAR(255) NULL
);

